# Generated by ChatGPT
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('escrows', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerKYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_legal_name', models.CharField(max_length=255)),
                ('national_id_number', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('address', models.TextField()),
                ('occupation', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('license_number', models.CharField(max_length=100)),
                ('license_state', models.CharField(max_length=100)),
                ('brokerage_firm_name', models.CharField(max_length=255)),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='brokerkyc', to='escrows.escrowparticipant')),
            ],
        ),
        migrations.CreateModel(
            name='BuyerKYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_legal_name', models.CharField(max_length=255)),
                ('national_id_number', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('address', models.TextField()),
                ('occupation', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_of_funds', models.CharField(blank=True, max_length=255, null=True)),
                ('tax_id', models.CharField(blank=True, max_length=100, null=True)),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='buyerkyc', to='escrows.escrowparticipant')),
            ],
        ),
        migrations.CreateModel(
            name='SellerKYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_legal_name', models.CharField(max_length=255)),
                ('national_id_number', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('address', models.TextField()),
                ('occupation', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_of_funds', models.CharField(blank=True, max_length=255, null=True)),
                ('tax_id', models.CharField(blank=True, max_length=100, null=True)),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sellerkyc', to='escrows.escrowparticipant')),
            ],
        ),
    ]
